version: "3.7"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    environment:
      - UID=${PUID}
      - GID=${PGID}
    volumes:
      - ./.homer/config.yml:/www/assets/config.yml
      - homer-assets:/www/assets
    expose:
      - 8080
    networks:
      - dashboard
      - reverse-proxy
    restart: unless-stopped
    
  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - fpm=false
      - branch=v2-master
    volumes:
      - organizr-config:/config
    expose:
      - 80
    networks:
      - dashboard
      - reverse-proxy
    restart: unless-stopped

volumes:
  homer-assets:
    name: homer-assets
  organizr-config:
    name: organizr-config

networks:
  dashboard:
    name: dashboard
  reverse-proxy:
    external: true