version: "3.7"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    environment:
      - UID=${PUID}
      - GID=${PGID}
    volumes:
      - homer-assets:/www/assets
    expose:
      - 8080
    networks:
      - dashboard
      - reverse-proxy
    restart: unless-stopped

volumes:
  homer-assets:
    name: homer-assets

networks:
  dashboard:
    name: dashboard
  reverse-proxy:
    external: true
