version: "3.7"

services:
  homer:
    image: b4bz/homer
    environment:
      - UID=${PUID}
      - GID=${PGID}
    volumes:
      - ./homer/assets:/www/assets
    expose:
      - 8080
    restart: unless-stopped