version: "3.7"

services:
  heimdall:
    image: linuxserver/heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.heimdall/config:/config
    ports:
      - 80:80
    restart: unless-stopped
